[package]
name = "year2021"
version = "0.22.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = {path = "../common"}
itertools = "0.14"
prse = "1.2"
anyhow = "1.0"