[package]
name = "year2019"
version = "0.17.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = {path = "../common"}
itertools = "0.13"
prse = "1.1"
anyhow = "1.0"
