[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2021"

[features]
verbose = [] #may be "verbose", "err" or none

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-ini = "*"
minreq = {version = "*", features = ["https"] }
regex = "*"
lazy_static = "*"
rust-crypto = "*"
unicode_categories = "*"
itertools = "*"