[package]
name = "advent_of_code"
version = "0.3.0"
edition = "2021"

[features]
verbose = []
err = []
default = ["verbose"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-ini = "*"                                      # common::settings
minreq = {version = "*", features = ["https"] }     # common::network

regex = "*"                                         # wherever needed
itertools = "*"                                     # wherever needed
scan_fmt = "*"                                      # wherever needed

once_cell = "*"                                     # will move to std

rust-crypto = "*"                                   # common::md5Hasher
unicode_categories = "*"                            # 2021/12
serde_json = "*"                                    # 2015/12, 2022/13
num = "*"                                           # 2019/10, 2019/12 - gcd, lcd

clap = { version = "*", features = ["derive"] }     # arguments parser
fancy-regex = "*"                                   # backreferences
