[package]
name = "advent_of_code"
version = "0.2.0"
edition = "2021"

[features]
verbose = []
err = []
default = ["verbose"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-ini = "*"                                      #common
minreq = {version = "*", features = ["https"] }     #common
regex = "*"                                         #whereever needed
once_cell = "*"                                     #lazy_static is depricated
rust-crypto = "*"                                   #2015/4, 2016/5
unicode_categories = "*"                            #2021/12
itertools = "*"                                     #whereever needed
json = "*"                                          #2015/12
text_io = "*"                                       #2019/12, but it should grow
num = "*"                                           #2019/10, 2019/12 - gcd, lcm