[package]
name = "aoc"
version = "0.3.0"
authors = ["Pavloslav <pavloslav@ukr.net>"]
edition = "2018"

[dependencies]
rust-ini = ">=0.9.12"
quick-error = "*"
# reqwest = {version = "*", features = ["blocking"] }
anyhow = "*"
minreq = {version = "2.2.1", features = ["https"] }