[package]
name = "aoc2021_4"
version = "0.1.0"
authors = ["Pavloslav <pavloslav@ukr.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc = { path = "../aoc" }