[package]
name = "year2018"
version = "0.12.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = {path = "../common"}
itertools = "0.12"
once_cell = "1.19"
prse = "1.1"
anyhow = "1.0"