[package]
name = "year2016"
version = "1.25.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = {path = "../common"}
itertools = "0.13"
prse = "1.1"
regex = "1.10"
anyhow = "1.0"