[package]
name = "year2023"
version = "0.16.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = {path = "../common"}
prse = "1.1"
itertools = "0.13"
anyhow = "1.0"