[package]
name = "year2023"
version = "0.16.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = {path = "../common"}
prse = "1.2"
itertools = "0.14"
anyhow = "1.0"