[package]
name = "year2020"
version = "0.19.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = {path = "../common"}
prse = "1.2"
regex = "1.11"
anyhow = "1.0"