[package]
name = "year2017"
version = "1.25.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = {path = "../common"}
prse = "1.2"
anyhow = "1.0"